services:
  keycloak:
    build: .
    image: my-keycloak:latest
    container_name: keycloak
    ports:
      - "8200:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_LOG_LEVEL=debug
      - KC_HTTP_ENABLED=true
#      - KC_SPI_PROVIDERS_PATH=/opt/keycloak/providers/
      - KC_SPI_EVENTS_LISTENER=custom-event-listener
#    command: ["start-dev"]
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak

